language: rust
rust:
- stable
sudo: false
os:
- linux
addons:
  apt:
    packages:
    - libudev-dev
cache:
  directories:
  - "$HOME/.cargo"
  - target
env:
  matrix:
  - CARGO_FEATURES=
  - CARGO_FEATURES=udev
  global:
  - CARGO_QUIET=
  - CARGO_INCREMENTAL=0
  - secure: rENtlLbnU+8/Qf6J1rIbnIpGvC1wTNtQJQ1FjIfBdwr6fTIq8nz3GtrTPO8emWezEwXji9JVD9ZnNkgrV9SS3j4iO0Km7TVJDwge1cs4dR3ArkzN67s2+06EjUnyOQwyXOWg95Pw/smPjNaUqwx122PwWtGhKVV2gddDV12cCaf5AlrqlPZlPXCSRhldUh/CH1T4rVebAYhBruROp2vNvlrBMy6kghCpAPunFvRJwAYo49wi6IsQHTTXv4NM7M3Yx+NHOxo3ljlPQD4wSyyu7kWGsTMLAbmQjvxe2BjnrO+ctW9hW5NZnZgFv/FyHZF0Ev/gM7sh5bbS8HKIRBZVjvrVwXnyhYVwCUKFOBjfmjFeYuAn2RsLLRU8rFM2H/3d0htSo1lfmDMNg839QsoQLQ3p2w0J836LhuIGoBaBhAQZ80YXG68sCGe7tEZjogRGFOMCElMTcy3d3H0zFZtr/piyw+CyqIQrSaZigFuOn0g9VIuEFvwOtcjRB6sziMYysZXNPV7nm8MrYcI7huDv3FiqkGa30379DZVLPzMAUSLB/z7KIaisy2aj87vFHq4RwaJs5P7bDGUDTvb5Xga6uOHqJcWicti0J94TkGr5AAStlSxGhvqtbuJ6C19eO//H3T/BwMRw55rusebg7P31xPR4xKlx4ryolY+DFjxUdGI=
  - secure: PASMn+NlikTe9l66qFVfYVv4L4CswWzTlUfA/zVSz8tVntw88MLBYz8eHjXNtv3KZgAlvNMRJBlZs/UU0iA304ltLbX4E6lCVD9ChoHOYOW470RmSxiz8U95GNQ1TtL+V19408ZF6HfeS94ZLrvUCGxesLcvcuK3vNP3SCN3CVcJZ+almy/V4REjluTBTSZF1TuhX6dZMybvk5yBmJxwWOujt1lZRDeH62kcCpuymb320h7k5FY0eY665DhJ8hxZeQ8EYbVRlOztG1MXtP21nleB35n/WOoks1h7SlS7eoQiT6RZvDqNbn/OfJBQBhyp7YNK6oAVo1/SBh+l9E5fRV08QG0WwFwWewv5JlvxIINQkSflzSpbxP/xZDY6r94xh5nmDcAfBkZmVoOSGkjuJOtJtEWfQNtdwCae/ynmbkb5/+VS0RPoSVCcgS4L6Z6KVjKsqPR74hVOjwv6TCvaiRkxy8A7MyD2Zobye42Ub67+4jCSJ84oKZf5JyOgqcI4dDRfEbQU03iFGn0jKRs0rN21P1dCErArB1JcOg3+vWtsjubw/AB5+KOTbWMLciWdB8qioGFfq+iFSed4ipSajqziZwShSYeXQSBqOjTUgrVj9wkZ8IQsX6cOpjbNs2sH5UVISGBm1Q340DUIEjsoNFPHuzBhIgjLBz4p/oLCtD8=
before_install:
- curl -L https://github.com/arcnmx/ci/archive/0.2.tar.gz | tar -xzC $HOME && . $HOME/ci-0.2/src
script:
- cargo test
- cargo build
deploy:
  provider: script
  script: 'true'
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_RUST_VERSION = stable && $CARGO_FEATURES = udev"
before_deploy:
- cargo doc
- cargo package
after_deploy:
- cargo pages-publish
- cargo publish
