(function() {var implementors = {};
implementors["ddc"] = ["impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"ddc/commands/struct.GetVcpFeature.html\" title=\"struct ddc::commands::GetVcpFeature\">GetVcpFeature</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"ddc/commands/struct.SetVcpFeature.html\" title=\"struct ddc::commands::SetVcpFeature\">SetVcpFeature</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"ddc/commands/struct.SaveCurrentSettings.html\" title=\"struct ddc::commands::SaveCurrentSettings\">SaveCurrentSettings</a>","impl&lt;'a&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"ddc/commands/struct.TableWrite.html\" title=\"struct ddc::commands::TableWrite\">TableWrite</a>&lt;'a&gt;","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"ddc/commands/struct.TableRead.html\" title=\"struct ddc::commands::TableRead\">TableRead</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"ddc/commands/struct.CapabilitiesRequest.html\" title=\"struct ddc::commands::CapabilitiesRequest\">CapabilitiesRequest</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"ddc/commands/struct.TableResponse.html\" title=\"struct ddc::commands::TableResponse\">TableResponse</a>","impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html\" title=\"trait core::marker::Copy\">Copy</a> for <a class=\"struct\" href=\"ddc/commands/struct.GetTimingReport.html\" title=\"struct ddc::commands::GetTimingReport\">GetTimingReport</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
